language: node_js
node_js:
  - "6.0"
before_install:
  - npm install -g bower
  - npm install -g gulp
script: gulp build
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  provider: script
  script: deploy.sh
  on:
    all_branches: true
   