language: node_js
node_js:
  - "6.0"
before_install:
  - npm install -g bower
  - npm install -g gulp
script: gulp build
deploy:
  provider: azure_web_apps
  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  site: hottowel       # If AZURE_WA_SITE isn't set
